### PR TITLE
Update Frontend

### PR DESCRIPTION
**Pull request by smart-hede**
https://bunzz-test.atlassian.net/browse/BUNZZ1-452

### CODE REVIEW

**Review by NailKhalimov — COMMENTED** [review]
@smart-ticky 
Thank you for your work!
Basically, everything looks fine. Could you please record a video of how it looks like?
Also please check linter error

**Comment by smart-hede** [comment]
okay, thank you

**Comment by smart-hede** [comment]
https://user-images.githubusercontent.com/68897116/222340277-4cf656cb-fe39-49a5-a50c-2cbbd5bbc942.mp4

**Comment by NailKhalimov** [comment]
@smart-ticky 
Thank you, Yano!
Could you please other tabs on the staking page?

**Comment by smart-hede** [comment]
> @smart-ticky Thank you, Yano! Could you please other tabs on the staking page?

that means you want to see how the other buttons works?

**Comment by NailKhalimov** [comment]
@smart-ticky 
Exactly!

**Comment by smart-hede** [comment]
https://user-images.githubusercontent.com/68897116/223030373-57ef813d-4f0e-45ea-ac32-a550d27dcc66.mp4

**Review by NailKhalimov — APPROVED** [review]
@smart-ticky 
Thank you! Good work!
LGTM!

**Pull request merged**
